
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

server:
  shutdown: graceful
  port: 8090

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: example-spring-security-jwt

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks
#          jws-algorithms: RS256
#          public-key-location: classpath:jwts/rsa_public.isa

